/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 1.2 */
/* Sun Jan 05 12:24:04 2025 */

/* parameterized module instance */
efb __ (.tc_clki( ), .tc_rstn( ), .tc_int( ), .tc_oc( ));
