/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 1.2 */
/* Sun Aug 26 15:55:55 2018 */

/* parameterized module instance */
efb __ (.tc_clki( ), .tc_rstn( ), .tc_int( ), .tc_oc( ));
